vscode_extensions:
  - charliermarsh.ruff
  - cschlosser.doxdocgen
  - eamodio.gitlens
  - foxundermoon.shell-format
  - github.vscode-pull-request-github
  - llvm-vs-code-extensions.vscode-clangd
  - ms-azuretools.vscode-docker
  - ms-python.debugpy
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-vscode.cpptools-extension-pack
  - ms-vscode.remote-explorer
  - ms-vscode-remote.vscode-remote-extensionpack
  - nvidia.nsight-vscode-edition
  - redhat.vscode-xml
  - redhat.vscode-yaml
  - streetsidesoftware.code-spell-checker
  - tamasfe.even-better-toml
  - timonwong.shellcheck
  - twxs.cmake
  - yzhang.markdown-all-in-one
