ci:
  autofix_commit_msg: "style(pre-commit-optional): autofix"
  # we already have our own daily update mechanism, we set this to quarterly
  autoupdate_schedule: quarterly
  autoupdate_commit_msg: "ci(pre-commit-optional): quarterly autoupdate"

repos:
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.14.2
    hooks:
      - id: markdown-link-check
        args: [--quiet, --config=.markdown-link-check.json]
