# @package _global_

trainer:
  _target_: lightning.Trainer
  max_epochs: 10
  accelerator: gpu
  devices: 1
  precision: 32-true
  log_every_n_steps: 50
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 1
  enable_progress_bar: true
  enable_model_summary: true
